### ISSUE TITLE
Language Barrier

### ISSUE THREAD

**Issue by AyoobN** [tprigent/kinesia#1]
Hi, 

Is it possible to change the main language of the program to English ? 

Thanks

**Comment by tprigent** [comment]
Hello,
This project was not thought to be translated, that's why all the interface is written in French.
In addition, the software does not meet the security criteria for medical data. It cannot therefore be used by a professional, that's why we concentrate only on our mother language.
However, if you want to contribute to the project and translate it, don't hesitate ;)
